### ISSUE TITLE
Application asks for Messenger Login

### ISSUE THREAD

**Issue by 3esmit** [Kuchiriel/whatsapp-unofficial-client#1]
This don't look like a WhatsApp client.

**Comment by Kuchiriel** [comment]
I have updated a new whats.html file, you can copy the code from the repository and replace in your local file, or install things again.

**Comment by ryukinix** [comment]
Liar!

**Comment by Kuchiriel** [comment]
This was the most hilarious commit that i have done. xD

**Comment by ryukinix** [comment]
LOOL

Fix that hurry, @Kuchiriel. You fucking with the life of end-users like @3esmit.

![lain-relax](https://cloud.githubusercontent.com/assets/7642878/13349059/22128cb6-dc56-11e5-81c7-c932bb3d08f2.jpg)

**Comment by Kuchiriel** [comment]
Fixed, I'm dying.

**Comment by onlurking** [comment]
![screenshot_2016-02-26_05-02-00](https://cloud.githubusercontent.com/assets/10618352/13349271/7fe9d06e-dc57-11e5-9f16-6a3dfe762dc6.png)
Just a minor typo, no problem at all.

**Comment by ryukinix** [comment]
Minor typo? A completely domain? Sarcasm is so nice.

**Comment by Kuchiriel** [comment]
The good news is that i have removed beeg.com just in time.

**Comment by 3esmit** [comment]
sei la nao entendi.
![20160226162755](https://cloud.githubusercontent.com/assets/224810/13369101/e4217690-dccf-11e5-9f25-9a7b2aafc69e.jpg)

**Comment by Kuchiriel** [comment]
BR é um câncer, ta em toda parte. AEYGAEYEA

**Comment by ryukinix** [comment]
Sickly
